# Generated by Django 4.2.4 on 2023-08-08 20:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_uploadedpdf_pdf_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='pdf_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
