# Generated by Django 4.2.4 on 2023-08-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_uploadedpdf_pdf_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedpdf',
            name='pdf_file_path',
        ),
    ]
