# Generated by Django 4.2.4 on 2023-08-08 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_uploadedpdf_pdf_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedpdf',
            old_name='pdf_file',
            new_name='PDF_file',
        ),
    ]
